### ISSUE TITLE
archivo modFunctionSpecs.txt

### ISSUE THREAD

**Issue by yuan-cherish** [Cajica-mex/SOFL-test-case-generation#1]
Disculpe, ¿me puede dar un archivo llamado modFunctionSpecs.txt para que pueda ejecutar este programa?

**Comment by WeirdoZz** [comment]
I want the txt file too.I would appreciate it greatly if you could give that.

**Comment by Cajica-mex** [comment]
I do not longer have that file, I checked my specs files and that one it's not there. I think I have the rest of the files.
